### ISSUE TITLE
Build a board of UX inspiration

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/scouts#5]
In this issue we are trying to get a better sense of the type of user experience we want to try and build for our users i.e. the best way for them to interact with our digital tool in order to achieve their needs.

This includes:
- user experiences our user personas know and like
- inspiration from platforms that we can use for how users might interact with our own digital platform
- what apps / websites do your users use?
- feedback on the MVP re UX

---

### Please watch below videos and check Acceptance Criteria for further instructions of how to do this exercise

**Please try and comment on this issue with your feedback by the end of this week latest (27/11)**

1. - [ ] Using the template below, write out the digital tools that you like **the flow** of/think our users personas will like

**Template:**
- App/website name:
- App/website link:
- The specific flow you like (with link or a few screenshots if possible!) and a description of why you and our users would like it. Why do you feel it's useful to look at with our project in mind?

2. - [ ] Please list in the comments below any particular feedback on the current MVP you think is important to consider

### Video explanation
https://www.loom.com/share/dd3b43f90dde47c4be01835d7cf3e3a2

**Comment by jema28** [comment]
### Example:

**App/website name:** Text

**App/website link:** Text

**The specific flow you like (with link or a few screenshots if possible!) and a description of why you and our users would like it. Why do you feel it's useful to look at with our project in mind?**
Text

**Comment by AndrewBarber** [comment]
# Exercism

**App/website name:** Exercism

**App/website link**: [Exercism.io](https://exercism.io)

**The specific flow you like (with link or a few screenshots if possible!) and a description of why you and our users would like it. Why do you feel it's useful to look at with our project in mind?**

While not related to the subject matter, I like the following:

The initial dashboard shows *tracks* with which you can dive in to study/learn, it provides a visually appealing area to pick and choose what you want to learn that session.

Once into the challenge view, it gives a nice layout of the learning (instructions in this case) on the left and actionable items on the right, as well as links to further learning materials.

**Comment by StephanieRainey** [comment]
App/website name: PuralSight website

App/website link: https://www.pluralsight.com

The specific flow you like (with link or a few screenshots if possible!) and a description of why you and our users would like it. Why do you feel it's useful to look at with our project in mind?
Website with lots of courses available.  There's a lot of information there for users to browse or search.  I like their search functionality, it's very quick and it displays both "Paths" and "Courses".  The "Paths" concept is good because it gives a range of courses with are recommended to learn a topic which might be relevant to Scout tasks.  Also has individual "Courses" if want to do a very specific topic.  I like the filter options so can be filtered by Roles and also by Skill level which might be very useful as Scout volunteers will have a wide range of different skill levels.  There are skill level tests which assess the users ability which would be extremely useful if we could do something similar for Scout volunteers.  

![Image 1](https://user-images.githubusercontent.com/75124400/100469311-e0a0de00-30cd-11eb-8c10-28e4824debf3.JPG)
![Image 2](https://user-images.githubusercontent.com/75124400/100469314-e1397480-30cd-11eb-8ec4-6fe5ba26cc18.JPG)
![Paths and Courses sections](https://user-images.githubusercontent.com/75124400/100469317-e1d20b00-30cd-11eb-8096-4068c037f232.JPG)
![Search filters available](https://user-images.githubusercontent.com/75124400/100469318-e1d20b00-30cd-11eb-8260-a9b8cb717ce2.JPG)
![Search functionality](https://user-images.githubusercontent.com/75124400/100469319-e26aa180-30cd-11eb-83fc-8ef396d19dfc.JPG)
![Test skill level](https://user-images.githubusercontent.com/75124400/100469322-e26aa180-30cd-11eb-8228-018481af6ff4.JPG)

**Comment by StephanieRainey** [comment]
**App/website name:** Be My Eyes app

**App/website link:** https://www.bemyeyes.com/

**The specific flow you like (with link or a few screenshots if possible!) and a description of why you and our users would like it. Why do you feel it's useful to look at with our project in mind?**
Good example of microvolunteering.  Was quick and easy to register as a volunteer so good onboarding process.  Really convenient to use because volunteers don't have to commit a lot of time to volunteer, automatically get a call when someone requires help, call normally only lasts a few seconds, no pressure to answer the call because multiple volunteers contacted at the same time, calls through the app so good data protecting because personal contact details aren't shared.  Good for users because they know they are getting someone able to help them, they get an instant response because the app keeps calling people until someone answers the call.  The app currently is segmented into different languages but for the Scout digital champions element if we used a similar concept but segmented it by skills then the calls would go to relevant contacts.

**Comment by StephanieRainey** [comment]
**App/website name:** Barclays Digital Eagles

**App/website link:** https://www.barclays.co.uk/digital-confidence/eagles/
https://www.youtube.com/playlist?list=PLecqH2uhOR0ZEGlDyEnB4h49_YX7LaJOS

**The specific flow you like (with link or a few screenshots if possible!) and a description of why you and our users would like it. Why do you feel it's useful to look at with our project in mind?**
Videos of training accessible to anyone.  Most people are able to access youtube and find it easy to watch a video to learn how to do something new.

![Barclays Digital Eagles](https://user-images.githubusercontent.com/75124400/100470518-47bf9200-30d0-11eb-9586-aaf8dc27d3e0.JPG)

**Comment by StephanieRainey** [comment]
**App/website name:** GCF Global

**App/website link:** https://edu.gcfglobal.org/en/
![GCF Global](https://user-images.githubusercontent.com/75124400/100470810-dd5b2180-30d0-11eb-9950-96a1d9021cd0.JPG)


**The specific flow you like (with link or a few screenshots if possible!) and a description of why you and our users would like it. Why do you feel it's useful to look at with our project in mind?**
Website with lots of training for users.  Split into different topics.  When users select a topic e.g. "Computer Basics", there's a range of tutorials/training.  I like how it's split into sections so users would be able to skip sections they are comfortable with or leave and return at a different stage.

**Comment by StephanieRainey** [comment]
**App/website name:** Talkinsights website

**App/website link:** https://www.talkinsights.com/

**The specific flow you like (with link or a few screenshots if possible!) and a description of why you and our users would like it. Why do you feel it's useful to look at with our project in mind?**
Although this website has a very different purpose from the Scout project, I really like that it remembers where you are in the journey.  The website conducts surveys, the users are emailed a link, when the user clicks on a link on their mobile but don't complete the survey the website remembers where you got to and you can go back into the survey again even on a different device and continue where you left off.  For Scouts this might be beneficial for training in case they don't manage to complete the training in one session, especially if the training isn't bite-sized.
